### ISSUE TITLE
Less secure lowkiq dashboards

### ISSUE THREAD

**Issue by arumugaraja-thirumani** [bia-technologies/lowkiq#13]
Anyone can access lowkiq dashboards without any restrictions.

To restrict accessing lowkiq dashboard, we may need to configure separate authentication in app where we are using lowkiq.
I have created a PR for fixing the same,
https://github.com/bia-technologies/lowkiq/pull/12

Please have a look

**Comment by darkleaf** [comment]
Thanks for your attention.

You can protect Lowkiq dashboard in your app by yourself. No changes are required for Lowkiq.
Anyone can choose any technique.  

```ruby
lowkiq = Rack::Auth::Basic.new(Lowkiq::Web) do |username, password|
  username == ENV.fetch('LOWKIQ_USERNAME') && password == ENV.fetch('LOWKIQ_PASSWORD')
end

Rails.application.routes.draw do
  #...
  mount lowkiq => '/lowkiq'
  #...
end
```
