### ISSUE TITLE
Smooth shard count transition is not feasible

### ISSUE THREAD

**Issue by PremSundar** [bia-technologies/lowkiq#14]
Based on the load, shard count of the workers should allowed to be changed.
But with the existing approach, changing the shard count would result in jobs getting executed out of the enqueued order. 
So, smooth shard count transition should be handled in order to avoid this. 

LMK your concerns on this issue and i am glad to contribute.

**Comment by darkleaf** [comment]
I don't understand the question. Can you provide an example?
Do you read [this](https://github.com/bia-technologies/lowkiq#changing-of-workers-shards-amount)?

**Comment by PremSundar** [comment]
Yes I've read that. It's possible to change the shards_count by changing the queue name but at the cost of disabling the enqueue of new jobs till the queue gets empty. Not all the applications can afford that.
Some 24/7 applications would want to be persistent that it cannot stop listening or disable the enqueue of jobs. In such cases, change of shard_count without losing data would become very difficult. 
So, in order to make lowkiq compatible for all kinds of applications, this shard count change has to be addressed within lowkiq. I hope this clarifies.

**Comment by darkleaf** [comment]
I have a thought.
For example, you have a web server process and a lowkiq process.
You can increase `shards_count`  by factor 2 or 3 and deploy this change only for a web server.
After some delay you should deploy lowkiq server with this changes.
In this time gap old lowkiq performs jobs with old sharding structure.
Please see the [id_to_shard](https://github.com/bia-technologies/lowkiq/blob/a811e747a8d04611967fa180457f7cd30e9f6768/lib/lowkiq/queue/queue.rb#L157-L159) method.
You have single shard and jobs with id 0, 1, 2, 3. Imagine that `Zlib.crc32` just returns its argument. 
Before changes : shard-0 - 0, 1, 2, 3
Transition: shard-0 - 0, 1, 2, 3; shard-1 - 1, 3
Waiting for old jobs:  shard-0 - 0, 2; shard-1 - 1, 3
Run new lowkiq.

**Comment by PremSundar** [comment]
There are few cases in which this doesn't work. For instance, after shard_count change in server process, there can be few job ids which could take some of the other old shards, that would be processed by the lowkiq worker(without sc change).In the following example, job_id 5 gets stored in shard_1 before change and shard_2 after change, then job_id 5 would miss the original order.
old_sc - 2
new_sc - 4
before:-
shard_1 - 1, 3, 5
shard_2 - 2, 4, 6
after:-
shard_1 - 1
shard_2 - 2, 5
shard_3 - 3, 6
shard_4 - 4

**Comment by darkleaf** [comment]
Please count shards and jobs from zero.

> would miss the original order.

The web server will enqueue jobs into a new sharding structure. 
Old lowkiq server will process **only** old shards.
New jobs for new shards will not be processed.
When all old jobs will be processed you can start new lowkiq server.  
So job's order will be persistent. But you will have a delay with new shards.

***

> Yes I've read that.

> If you can disable adding of new jobs, wait for queues to get empty and deploy the new version of code with changed amount of shards.
> If you can't do it, follow the next steps:

So there are two cases: stopping and live migration. The second case is yours.

**Comment by PremSundar** [comment]
Yeah I agree. The procedure you have stated above would work without missing any order and as you've mentioned there would be a delay with new shards.

Along with the delay, this process requires some manual intervention. Also if there is a considerable amount of morgue jobs, that would make an impact in both manual efforts and delay in processing the new shard jobs. As the application scales, we can't afford to follow these manual procedures.

So, What i'm proposing is to move the shard migration logic within lowkiq so that to reduce the manual intervention in lowkiq deployment and no unpredictable delays. Pls go through this PR #15    and check if this works.
