### ISSUE TITLE
Issue in Jobs count - Can Documentation / API help?

### ISSUE THREAD

**Issue by ritikesh** [bia-technologies/lowkiq#19]
Hi, 

We are running lowkiq in production. Suddenly, we notice that there are certain jobs that are dead - in the sense, they're listed in the enqueued, but even with 0 traffic, those jobs don't get picked. We have some 40 odds dead jobs lying around unpicked. How do we trace the same?

**Comment by darkleaf** [comment]
Hi!

> We are running lowkiq in production. 

That's cool!

Please look at the attribute `perform_in` of an enqueued job.
Click at a number in the "Enqueued" column on the dashboard.
<img width="1189" alt="Снимок экрана 2020-09-04 в 19 08 26" src="https://user-images.githubusercontent.com/1124593/92254994-c5656e80-eee2-11ea-8540-dd98ec28b28d.png">

The value of `perform_in` should be the UNIX timestamp. I think you just have the wrong value in this field. Probably you use timestamps with milliseconds.

When you fix this problem you can press "perform all jobs now".

**Comment by ritikesh** [comment]
> Probably you use timestamps with milliseconds.

Is that a problem? Using timestamps in milliseconds? Although, I can confirm, no we are not.

**Comment by darkleaf** [comment]
Yes, it is a problem.
`perform_in` must be filled by a timestamp in **seconds**, not milliseconds.

You may not specify `perform_in` at all:

```ruby
ATestWorker.perform_async [
  { id: 0 },
  { id: 1, payload: { attr: 'v1' } },
  { id: 2, payload: { attr: 'v1' }, score: Time.now.to_i, perform_in: Time.now.to_i },
]
# payload by default equals to ""
# score and perform_in by default equals to Time.now.to_i
```

**Comment by ritikesh** [comment]
Yes, in fact, we do not specify `perform_in`. Will try digging deeper into this, thanks.

**Comment by darkleaf** [comment]
Anyway, check `perform_in`, it should have properly value. Also, check `retry_count`.

**Comment by darkleaf** [comment]
Look at https://github.com/bia-technologies/lowkiq/blob/master/lib/lowkiq/schedulers/lag.rb#L15

Also, you can attach a screenshot of the dashboard and enqueued page. And please write the current timestamp.

**Comment by ritikesh** [comment]
We cleared the lags manually by clearing redis keys as our monitoring systems was constantly notifying us. Will share details if I see it again. I can confirm that perform_in was a unix timestamp without decimals and Retries were empty.

**Comment by ritikesh** [comment]
@darkleaf if we are deleting a worker - removing the worker class after draining the older jobs, will there be a shard rebalancing issue? Do we still need to run a script to migrate jobs?

**Comment by darkleaf** [comment]
Each worker has its own shards, so you can remove it when you will. 

I still don't have full information to solve the problem. Can you provide a minimal reproducible example of this problem?

**Comment by ritikesh** [comment]
We are not able to reproduce this. It only happened once when there was a sudden surge in load in our production system. Will keep this thread posted if I see it happen again. 

Thanks for your time.
