### ISSUE TITLE
Performance of lowkiq

### ISSUE THREAD

**Issue by fw-vimal** [bia-technologies/lowkiq#20]
We ran a load test on lowkiq. Here are our worker details:

1. Worker 1: shards - 75, batch_size - 30
2. Worker 2: shards - 50, batch_size - 30

threads_per_node - 50
number of nodes - 2
client_pool_size - 500
pool_timeout - 5
max_retry_count - 25
poll_interval - 1

We are using lag scheduler and we are not using hiredis.

We have an API which will push item to worker 1. Worker 1 push items to worker 2.

In our load testing, we tried to push 50k items to API. We used 5 process to generate load and each process will post 10000 items at the rate of 250 items per second in parallel. Overall, we were trying to calculate time taken by lowkiq (worker 1 and worker 2) to process 50k items.

Our observations:

Overall, we could see some lags between perform_async and perform call. I have listed some metric that we observed in load testing:

Item enqueued to worker 1 at 1606273149124 (in EPOC milliseconds), but the item is picked by worker 1 at 1606273200076. Processing time of worker 1 (including enqueuing item to worker 2) is 9 ms. We could see lag of 50 seconds. 

The lag in worker 2 for the same transaction is 3.5 seconds. The lag at worker 2 went upto 6 seconds in other transactions.

During load test, we could see enqueued items count increased upto 43k and it took 4 to 5 minutes to process 50k items.

We also tried running load test with following configuration and observed same behaviour.

1. Worker 1: shards - 75, batch_size - 30
2. Worker 2: shards - 50, batch_size - 30

threads_per_node - 65
number of nodes - 2
client_pool_size - 500
pool_timeout - 5
max_retry_count - 25
poll_interval - 1

We are also planning to merge worker 1 and worker 2 to reduce lag. But, we are not sure why lowkiq took 50 seconds (on avg) to pick item for processing. We observed same behaviour in our multiple runs. Are we missing some thing here? Are we running with right configuration?

Regards,
Vimal

**Comment by darkleaf** [comment]
Can you make an example project?

If you can not, please tell me how you insert items for Worker 1. What kind of `id` do you use? Do you set up `perform_in`?

Also, check that local time is synchronized on your servers.

**Comment by fw-vimal** [comment]
I will try to make an example project.

Sample id: 12:2d5b15c1a01e3e46db48cdc7db5286b651464361d6dd0a5d994d2cfc5d96a64e
I use following function to generate id: 

function gen_id(aid, iid, string1, string2, string3) {
    string3 ||= ''
    hash = Digest::SHA2.hexdigest("#{iid}:#{string1}:#{string2}:#{string3}")
    "#{aid}:#{hash}"
end

aid -> integer and mandatory field
string 1 and 2 are also mandatory fields. string 3 is optional string.

perform_in  = Date time in epoc seconds (User value. But in load test it is current time) I will check time synchronisation with my machine and server. 

perform_in can cause delay. Thanks for the inputs. I will change those as well and run tests.

**Comment by fw-vimal** [comment]
Thanks for your suggestions. Example -> https://github.com/vimsel25/lowkiq_load_test.git

Here, I have created a sample rails app which will accept following payload, do and process that through two worker. Kind of mimic our application. I have logged before and after at three stages of flow: 1. At controller, 2. At Manager worker and 3. At Processor worker. The time difference between completion of controller to starting manager's perform and the completion of manager's perform to staring processor's perform is what I am referring as delay. 

Let me know if I am missing something which caused this delay.

**Comment by darkleaf** [comment]
Thanks. Can you give me the script to generate the proper load?

```ruby
# config/lowkiq.rb
# frozen_string_literal: true

Lowkiq.poll_interval = 1
Lowkiq.client_pool_size = 500 # <=== It seems too big. Do you make 500 thread in your puma or lowkiq process?
Lowkiq.pool_timeout = 5
Lowkiq.threads_per_node = 100 # <=== It seems too big. Do you perform too many IO operations?

# handles worker shards across multiple process threads
Lowkiq.build_splitter = -> () do
  Lowkiq.build_by_node_splitter(
    ENV.fetch('LOWKIQ_NUMBER_OF_NODES').to_i,
    ENV.fetch('LOWKIQ_NODE_NUMBER').to_i
  )
end if Rails.env.production? || Rails.env.staging?

Dir["#{Rails.root}/app/workers/*.rb"].each do |file|
  require_dependency file
end

Lowkiq.on_server_init = lambda do
  puts "Lowkiq Server Started..."
end
```

```ruby
# config/redis.rb
# frozen_string_literal: true

config = YAML.load_file("#{Rails.root}/config/redis.yml")[Rails.env].with_indifferent_access
connection = Redis.new(config)

# <=== this **global** variable is not used
$redis = Redis::Namespace.new(config[:namespace][:others], redis: connection, warning: false)

if Rails.env.production?
  Lowkiq.redis = -> { Redis.new(config) } # <=== it's ok
else
  $lowkiq_redis = Redis::Namespace.new(config[:namespace][:lowkiq], redis: Redis.new(config), warning: false)

  # <=== it's not ok, you should create a new instance per lambda call
  # <=== so, maybe your problem is caused by this line  
  Lowkiq.redis = -> { $lowkiq_redis }
end

```

**Comment by darkleaf** [comment]
@fw-vimal @vimsel25 have you solved the problem?

**Comment by fw-vimal** [comment]
Hi @darkleaf, Apologies for the delay. Not ate. I made the suggested changes and run load test. I can still see delay in picking messages. I observed delay even if I push three messages in local.

**Comment by darkleaf** [comment]
I've removed all unused things and it works. https://github.com/darkleaf/lowkiq_load_test

Also, I've seen that there is a loading problem: the worker's duplication. I don't know changes in Rails 6. Maybe there are breaking changes and we should preload worker's classes in another way. But even with this issue, Lowkiq handles jobs instantly.

![lowkiq](https://user-images.githubusercontent.com/1124593/102089073-2d5a1800-3e35-11eb-80f3-1c9e7093fc22.gif)

**Comment by fw-vimal** [comment]
@darkleaf Thanks for sharing changes. Here is what I am facing even in https://github.com/darkleaf/lowkiq_load_test. When I post to dummy_api_controller, I log timings in log/app.log file. 

If you check the time difference between the log (which is the time difference between push to lowkiq in controller and worker perform call), it varies between 500 ms to 900 ms and it keeps increasing to some seconds in our load test. 

Eg: 

Completing DummyApiController generate_load method, uuid: f6df7c33-35c5-42d8-9e3b-abca7459929f, at: **1608135478460.8362**, resp_time: 35.66845703125
Starting Manager perform method, uuid: f6df7c33-35c5-42d8-9e3b-abca7459929f, at: **1608135479096.202**

**1608135479096.202 - 1608135478460.8362 => 635.3657**

Not sure something to do with rails 6. But this creates lot of lags and increases lags to minutes.

**Comment by darkleaf** [comment]
Yes, there is poll_interval. And 900 ms is less than 1 second. It's ok.

> Lowkiq.poll_interval = 1 - delay in seconds between queue polling for new jobs. Used only if the queue was empty at previous cycle or error was occurred.

> increasing to some seconds in our load test.

Can you provide this load test?
