### ISSUE TITLE
Identify whether the current process is Lowkiq server or not. Similar to Sidekiq.server?

### ISSUE THREAD

**Issue by ruban-thilak** [bia-technologies/lowkiq#31]
Sidekiq.server? is method in sidekiq. Inorder to identify whether the current terminal or process is Sidekiq server.

` def self.server?
    defined?(Sidekiq::CLI)
  end
`

This might be useful in runtime to identify and store logging/tracing information

**Comment by darkleaf** [comment]
There are `client_middlewares` and `server_middlewares`. Why you need `Lowkiq.server?`

**Comment by darkleaf** [comment]
Please see https://github.com/bia-technologies/lowkiq#execution

`bundle exec lowkiq -r ./config/environment.rb`

You can create a new file for example `config/lowkiq_environment.rb`

``` ruby
$lowkiq_server = true
require_relative './config/environment.rb'
```

and run `bundle exec lowkiq -r ./config/lowkiq_environment.rb`
